services:
  db:
    build: .
    container_name: fr_postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fakepassword
      POSTGRES_DB: frdatabase

  minio:
    image: minio/minio
    container_name: fr_minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
