services:
  db:
    build: .
    container_name: fr_postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fakepassword
      POSTGRES_DB: frdatabase

volumes:
  pgdata:
